### ISSUE TITLE
Using Canvas

### ISSUE THREAD

**Issue by eddyc** [charlieroberts/gibber.lib#11]
Hi, really enjoying getting to know this library, I was trying to use the Canvas object but it doesn't seem to be present in this version. Although there seems to be some code commented out in the built version of the library that relates to the Canvas object, is the Canvas object not really supported in this version?

**Comment by charlieroberts** [comment]
Hmmm... I just checked out the most recent version (via npm) and the following code worked fine. Maybe you could post your code?

```html
<html>

<head>
  <script src='./build/gibber.lib.js'></script>
</head>

<body></body>

<script>
Gibber.init()

a = EDrums('x*ox*xo-')
a.snare.snappy = 1

a.fx.add( Reverb() )

c = Canvas()

c.square( 200,200,200 )

c.fill( 'red' )


</script>

</html>
```

**Comment by eddyc** [comment]
Sorry for the noise, I had left out the call to Gibber.init, thanks for your help.
Ed

**Comment by charlieroberts** [comment]
No worries!
